import type { Metadata } from "next";
import { Signika_Negative } from "next/font/google";
import "./globals.css";

const signikaNegative = Signika_Negative({
  variable: "--font-signika-negative",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "UbuntuX",
  description: "Generated by UbuntuX",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${signikaNegative.variable} antialiased px-4 sm:px-6 md:px-8 lg:px-16 xl:px-24 overflow-x-hidden max-w-full`}
      >
        <div className="min-h-screen flex flex-col w-full max-w-full overflow-x-hidden">
          {children}
        </div>
      </body>
    </html>
  );
}
